package com.sd.vo;

// Generated 2015-5-18 9:04:31 by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Trespic generated by hbm2java
 */
@Entity
@Table(name="trespic")
public class Trespic  extends BaseVo implements java.io.Serializable {
	
	@Column(name="rp_id")
	private Integer rpId;
	@Id
	@Column(name="rp_Gid")
	private String rpGid;
	
	@Column(name="rp_url")
	private String rpUrl;
	
	@Column(name="rp_uploaderid")
	private Integer rpUploaderid;
	
	@Column(name="rp_date")
	private Date rpDate;
	
	@Column(name="rp_ip")
	private String rpIp;
	
	@Column(name="rp_width")
	private Integer rpWidth;
	
	@Column(name="rp_height")
	private Integer rpHeight;
	
	@Column(name="rp_angle")
	private String rpAngle;
	
	@Column(name="rp_small")
	private String rpSmall;
	
	@Column(name="rp_mid")
	private String rpMid;
	
	@Column(name="rp_updatetime")
	private Date rpUpdatetime;
	
	@Column(name="rp_isdel")
	private Integer rpIsdel;


	public String getRpGid() {
		return rpGid;
	}

	public void setRpGid(String rpGid) {
		this.rpGid = rpGid;
	}

	public Integer getRpId() {
		return this.rpId;
	}

	public void setRpId(Integer rpId) {
		this.rpId = rpId;
	}

	public String getRpUrl() {
		return this.rpUrl;
	}

	public void setRpUrl(String rpUrl) {
		this.rpUrl = rpUrl;
	}

	public Integer getRpUploaderid() {
		return this.rpUploaderid;
	}

	public void setRpUploaderid(Integer rpUploaderid) {
		this.rpUploaderid = rpUploaderid;
	}

	public Date getRpDate() {
		return this.rpDate;
	}

	public void setRpDate(Date rpDate) {
		this.rpDate = rpDate;
	}

	public String getRpIp() {
		return this.rpIp;
	}

	public void setRpIp(String rpIp) {
		this.rpIp = rpIp;
	}


	public Integer getRpWidth() {
		return this.rpWidth;
	}

	public void setRpWidth(Integer rpWidth) {
		this.rpWidth = rpWidth;
	}

	public Integer getRpHeight() {
		return this.rpHeight;
	}

	public void setRpHeight(Integer rpHeight) {
		this.rpHeight = rpHeight;
	}

	public String getRpAngle() {
		return this.rpAngle;
	}

	public void setRpAngle(String rpAngle) {
		this.rpAngle = rpAngle;
	}


	public String getRpSmall() {
		return rpSmall;
	}

	public void setRpSmall(String rpSmall) {
		this.rpSmall = rpSmall;
	}

	public String getRpMid() {
		return rpMid;
	}

	public void setRpMid(String rpMid) {
		this.rpMid = rpMid;
	}


	public Date getRpUpdatetime() {
		return this.rpUpdatetime;
	}

	public void setRpUpdatetime(Date rpUpdatetime) {
		this.rpUpdatetime = rpUpdatetime;
	}

	public Integer getRpIsdel() {
		return this.rpIsdel;
	}

	public void setRpIsdel(Integer rpIsdel) {
		this.rpIsdel = rpIsdel;
	}

}
